//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Wayne.Payment.Products.iXConfigurator.Template {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.wayne.com/ixconfig")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.wayne.com/ixconfig", IsNullable=false)]
    public partial class configurationTemplate {
        
        private product productField;
        
        private page[] pagesField;
        
        private task[] buildField;
        
        private task[] importField;
        
        /// <remarks/>
        public product product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public page[] pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(copy), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(delete), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(download), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(move), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(readXml), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(set), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(unset), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(unzip), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(writeXml), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(writeXmlTable), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(zip), IsNullable=false)]
        public task[] build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(copy), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(delete), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(download), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(move), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(readXml), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(set), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(unset), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(unzip), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(writeXml), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(writeXmlTable), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(zip), IsNullable=false)]
        public task[] import {
            get {
                return this.importField;
            }
            set {
                this.importField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class product {
        
        private string nameField;
        
        private string versionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class @unchecked {
        
        private object[] itemsField;
        
        private bool dummyField;
        
        public @unchecked() {
            this.dummyField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option", typeof(option))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(set))]
        [System.Xml.Serialization.XmlElementAttribute("unset", typeof(unset))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool dummy {
            get {
                return this.dummyField;
            }
            set {
                this.dummyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class option : element {
        
        private control itemField;
        
        private string labelField;
        
        private string keyField;
        
        private string requiredField;
        
        public option() {
            this.requiredField = "false";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("check", typeof(check))]
        [System.Xml.Serialization.XmlElementAttribute("combo", typeof(combo))]
        [System.Xml.Serialization.XmlElementAttribute("list", typeof(list))]
        [System.Xml.Serialization.XmlElementAttribute("radio", typeof(radio))]
        [System.Xml.Serialization.XmlElementAttribute("table", typeof(table))]
        [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
        public control Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class check : control {
        
        private @checked checkedField;
        
        private @unchecked uncheckedField;
        
        private bool defaultField;
        
        public check() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        public @checked @checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
            }
        }
        
        /// <remarks/>
        public @unchecked @unchecked {
            get {
                return this.uncheckedField;
            }
            set {
                this.uncheckedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class @checked {
        
        private object[] itemsField;
        
        private bool dummyField;
        
        public @checked() {
            this.dummyField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option", typeof(option))]
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(set))]
        [System.Xml.Serialization.XmlElementAttribute("unset", typeof(unset))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool dummy {
            get {
                return this.dummyField;
            }
            set {
                this.dummyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class set : task {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(writeXmlTable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(writeXml))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(readXml))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(unzip))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(zip))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(move))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(delete))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(download))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(copy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(unset))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(set))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class task {
        
        private string conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class writeXmlTable : task {
        
        private string fileField;
        
        private string xpathField;
        
        private string elementField;
        
        private string[] attributeField;
        
        private writeXmlCreateOption createField;
        
        private string tableField;
        
        private bool appendField;
        
        public writeXmlTable() {
            this.createField = writeXmlCreateOption.none;
            this.appendField = true;
        }
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public string element {
            get {
                return this.elementField;
            }
            set {
                this.elementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute")]
        public string[] attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(writeXmlCreateOption.none)]
        public writeXmlCreateOption create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool append {
            get {
                return this.appendField;
            }
            set {
                this.appendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public enum writeXmlCreateOption {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        xpath,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class writeXml : task {
        
        private string fileField;
        
        private string xpathField;
        
        private string valueField;
        
        private writeXmlCreateOption createField;
        
        public writeXml() {
            this.createField = writeXmlCreateOption.none;
        }
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(writeXmlCreateOption.none)]
        public writeXmlCreateOption create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class readXml : task {
        
        private string fileField;
        
        private string xpathField;
        
        private string keyField;
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string xpath {
            get {
                return this.xpathField;
            }
            set {
                this.xpathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class unzip : task {
        
        private string fileField;
        
        private string pathField;
        
        private bool overwriteField;
        
        public unzip() {
            this.overwriteField = false;
        }
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class zip : task {
        
        private string pathField;
        
        private string fileField;
        
        private bool overwriteField;
        
        public zip() {
            this.overwriteField = false;
        }
        
        /// <remarks/>
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class move : task {
        
        private string fromField;
        
        private string toField;
        
        private bool overwriteField;
        
        public move() {
            this.overwriteField = true;
        }
        
        /// <remarks/>
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class delete : task {
        
        private string pathField;
        
        /// <remarks/>
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class download : task {
        
        private string urlField;
        
        private string fileField;
        
        private bool overwriteField;
        
        public download() {
            this.overwriteField = true;
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class copy : task {
        
        private string fromField;
        
        private string toField;
        
        private bool overwriteField;
        
        public copy() {
            this.overwriteField = true;
        }
        
        /// <remarks/>
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool overwrite {
            get {
                return this.overwriteField;
            }
            set {
                this.overwriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class unset : task {
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(table))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(text))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(check))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(radio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(list))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(combo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class control : element {
        
        private string enabledField;
        
        public control() {
            this.enabledField = "true";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("true")]
        public string enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(section))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(control))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(table))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(text))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(check))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(radio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(list))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(combo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(option))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(page))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class element {
        
        private string visibleField;
        
        public element() {
            this.visibleField = "true";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("true")]
        public string visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class section : element {
        
        private string descriptionField;
        
        private option[] optionField;
        
        private string titleField;
        
        private string iconField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option")]
        public option[] option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class page : element {
        
        private string descriptionField;
        
        private element[] itemsField;
        
        private string summaryField;
        
        private string titleField;
        
        private string iconField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("option", typeof(option))]
        [System.Xml.Serialization.XmlElementAttribute("section", typeof(section))]
        public element[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class table : control {
        
        private bool editableField;
        
        private string[] textField;
        
        public table() {
            this.editableField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class text : control {
        
        private string valueField;
        
        private string hintField;
        
        private textRestriction restrictionField;
        
        private string patternField;
        
        public text() {
            this.restrictionField = textRestriction.none;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(textRestriction.none)]
        public textRestriction restriction {
            get {
                return this.restrictionField;
            }
            set {
                this.restrictionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public enum textRestriction {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        ipv4,
        
        /// <remarks/>
        ipv6,
        
        /// <remarks/>
        port,
        
        /// <remarks/>
        number,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class radio : control {
        
        private choice[] choiceField;
        
        private orientation orientationField;
        
        private string filterField;
        
        public radio() {
            this.orientationField = orientation.vertical;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("choice")]
        public choice[] choice {
            get {
                return this.choiceField;
            }
            set {
                this.choiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(orientation.vertical)]
        public orientation orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class choice {
        
        private task[] itemsField;
        
        private string nameField;
        
        private string valueField;
        
        private string filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(set))]
        [System.Xml.Serialization.XmlElementAttribute("unset", typeof(unset))]
        public task[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public enum orientation {
        
        /// <remarks/>
        vertical,
        
        /// <remarks/>
        horizontal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class list : control {
        
        private item[] itemField;
        
        private string filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public item[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class item {
        
        private task[] itemsField;
        
        private string nameField;
        
        private string valueField;
        
        private string filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("set", typeof(set))]
        [System.Xml.Serialization.XmlElementAttribute("unset", typeof(unset))]
        public task[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.wayne.com/ixconfig")]
    public partial class combo : control {
        
        private item[] itemField;
        
        private string filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public item[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
}
